### ISSUE TITLE
Also catch full URLs to bugzilla bugs

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/botzilla#13]
... and in this case, do not print the minified bug URL.

**Comment by evilpie** [comment]
We should revert this change. Matrix will already fetch the URL and display the important info inline.

**Comment by bnjbvr** [comment]
The channel admin can choose to disable URL previews for the room, which is why i implemented this in the first place, and a given user can also choose to enable/disable those previews, per room. This is too much trouble trying to fit all the possible settings, though, so I'll disable it instead.
