### ISSUE TITLE
Botzilla should ignore bugzilla links in reply messages

### ISSUE THREAD

**Issue by dannycolin** [bnjbvr/botzilla#17]
**Actual Behavior**

If you use the reply function in Matrix and the reply message contains a bugzilla link, Botzilla will show the bug title.

**Expected Behavior**

Botzilla should ignore bugzilla links in the blockquote of a reply.

**Additional information**

See [this screeshot](https://imgur.com/RO2mpvZ)

**Comment by tulir** [comment]
Relevant part of spec: https://matrix.org/docs/spec/client_server/latest#rich-replies

**Comment by bnjbvr** [comment]
Thanks for the issue and spec link!
