### ISSUE TITLE
Support mutli-line statuses for confession

### ISSUE THREAD

**Issue by mgaudet** [bnjbvr/botzilla#23]
I was a little surprised when [this](https://matrix.to/#/!CZEbuMfGYVdQMIBKeP:mozilla.org/$mHs13IzYygKpZKCy7LmXdeD8WWBz2C7WgI3OV-dT7iw?via=mozilla.org&via=igalia.com&via=matrix.org) confession generated an [entry using only the first line](https://robotzilla.github.io/histoire/?user=mgaudet:mozilla.org). 

IMO, multi-line status support would be nice.

**Comment by bnjbvr** [comment]
Interesting, I wonder if this is the [`event.content.body`](https://github.com/bnjbvr/botzilla/blob/master/src/index.js#L79) that's stripped (in which case we can't do anything), or if the [regexp](https://github.com/bnjbvr/botzilla/blob/master/src/modules/confession.js#L13) isn't broad enough to catch multiple lines.
