### ISSUE TITLE
Follow Matrix room upgrades

### ISSUE THREAD

**Issue by callahad** [bnjbvr/botzilla#29]
Sometimes Matrix rooms get upgraded to newer versions, as recently happened with `#fx-desktop-dev:mozilla.org`.

It would be nice if botzilla was able to follow upgrades and maintain its presence in the new room.

**Comment by bnjbvr** [comment]
Thanks! From skimming the docs of matrix bot sdk, this should be as easy as adding another mixin that does it, AutojoinUpgradedRoomsMixin. On the other hand, data tied to a room should be transferred to the upgraded room, requiring some SQL.

How can one test room upgrades for testing purposes? Is there a way to create rooms that will get upgraded on demand, to try the migrations?

**Comment by callahad** [comment]
Going off of memory, I believe the magic incantation is `/upgraderoom 6`

6 is kind of a magic number -- it's currently the latest version of the
room spec. You can "upgrade" to the same version, so you should be able to
repeat that command as many times as you want.

**Comment by bnjbvr** [comment]
Thanks! This made testing a breeze.
