### ISSUE TITLE
Show Bugzilla information when bug number or URL is detected in the chatroom

### ISSUE THREAD

**Issue by dannycolin** [bnjbvr/botzilla#5]
This is an other cool feature in Firebot that I think it'd be nice to port to Botzilla. When a bug number or URL is detected the bot show the status, reporter and title of the bug.

Here's the examples: 
```
username | bug 1566950
@firebot | https://bugzil.la/1566950 — DUPLICATE, nobody@mozilla.org — "abc.def" property in about:config, cannot be removed
```
Or
```
username | https://bugzilla.mozilla.org/show_bug.cgi?id=1566950
@firebot | https://bugzil.la/1566950 — DUPLICATE, nobody@mozilla.org — "abc.def" property in about:config, cannot be removed
```

**Comment by bnjbvr** [comment]
Thanks for opening an issue! I agree it was quite nice to be able to do this. Now Riot has URL preview, so just generating the URL as the bot does right now is sufficient to display this information (which is, if I understand correctly, all contained in the page's title).

That being said, Matrix rooms may disable URL preview, so implementing this would be needed in such a case.

**Comment by dannycolin** [comment]
> That being said, Matrix rooms may disable URL preview, so implementing this would be needed in such a case.

Yes, exactly. Also, as a user you can turn off URL preview. I personally turn them off because it shows an image that waste a lot of space vs. the one line posted by Firebot on IRC.
