### ISSUE TITLE
Use the Bugzilla REST API to query BMO instead of scraping html

### ISSUE THREAD

**Issue by globau** [bnjbvr/botzilla#9]
The bot hits the show_bug html endpoint instead of the much quicker and easier to consume REST API:

See https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug

By default the REST API returns almost all fields; make sure to use `include_fields` to return just the fields you're using.

example: https://bugzilla.mozilla.org/rest/bug/1603447?include_fields=summary,assigned_to,status,resolution

```
{
  "bugs": [
    {
      "summary": "Moving files lead to a weird double move in Phabricator",
      "assigned_to_detail": {
        "email": "nobody@mozilla.org",
        "real_name": "Nobody; OK to take it and work on it",
        "name": "nobody@mozilla.org",
        "nick": "nobody",
        "id": 1
      },
      "status": "RESOLVED",
      "resolution": "WORKSFORME",
      "assigned_to": "nobody@mozilla.org"
    }
  ],
  "faults": []
}
```

and against a non-public bug:

https://bugzilla.mozilla.org/rest/bug/1595329?include_fields=summary,assigned_to,status,resolution

```
{
  "documentation": "https://bmo.readthedocs.io/en/latest/api/",
  "error": true,
  "code": 102,
  "message": "You are not authorized to access bug 1595329. To see this bug, you must first log in to an account with the appropriate permissions."
}
```

**Comment by bnjbvr** [comment]
Great, it's going to make it easier (and remove the HTML parsing dependency), thanks for bringing this up!
